version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ctn
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_ctn
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - app_network

#volumes:
#  mysql_data:

networks:
  app_network:
    driver: bridge
