server:
  port: 9090  # Définit le port de ton serveur Spring Boot

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice_db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: # create    update
      ddl-auto: update  # Met à jour le schéma sans supprimer les données existantes
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Formate les requêtes SQL pour une meilleure lisibilité

logging:
  level:
    org.springframework.web: DEBUG
